services:
  - type: web
    name: url-shortener-api
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: REDIS_URL
        sync: false
      - key: BASE_URL
        value: https://trimurl-x10s.onrender.com
      - key: BASE_URL
        value: https://trimurl-x10s.onrender.com
